# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: ${MYSQL_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: huntDB-adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

volumes:
  huntDB-data:
    driver: local
